version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.8.0
    environment: 
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - elk-net


  kibanaweb:
    image: kibana:7.8.0
    ports:
      - "5601:5601"
      - "8089:8080"
    depends_on: 
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elk-net

  logstash_app:
    build: .
    depends_on: 
      - elasticsearch
      # - kibanaweb
    environment:
      - ELASTICSEARCH_HOST_PORT=http://elasticsearch:9200 
    volumes:
      - ./config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      # - ./config/logstash-docker.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./config/logstash-filebeat.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logs/:/tmp/logs/
    networks:
      - elk-net


networks:
  elk-net:
    external: true
