version: '3.7'
services:
  filebeat_1:
    image: docker.elastic.co/beats/filebeat:7.4.2
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml #Load Config
      - H:/ELK-Stack/APP_2/logs/:/tmp/APP_2/logs/ #File Directory for log
    command: ["-e" , "-d" , "*"]
    networks:
      - elk-net


networks:
  elk-net:
    external: true
